import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
const source = fs.readFileSync(new URL('../src/utils/crm.js', import.meta.url), 'utf8')
const u = await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`)
const page = fs.readFileSync(new URL('../src/pages/crm/CrmGreMarketing.jsx', import.meta.url),'utf8')
const form = fs.readFileSync(new URL('../src/pages/crm/CrmRecordForm.jsx', import.meta.url),'utf8')
const api = fs.readFileSync(new URL('../src/api/crmApi.js', import.meta.url),'utf8')
test('exactly five simplified tabs, no bonus or prototype presentation',()=>{assert.deepEqual(u.CRM_TABS,['Overview','Hotel Stays','Transport','Services & Gifts','All Records']);for(const value of ['initialGuests','initialRequests','BonusManagement','Assigned GRE','window.print','2026-07-21','wallet','exposure'])assert.ok(!page.includes(value),value)})
test('only super admin mutates',()=>{assert.equal(u.canMutateCrm('SUPER_ADMIN'),true);for(const role of ['DIRECTOR','ADMIN','MANAGER','RECEPTIONIST','CASHIER','DEALER'])assert.equal(u.canMutateCrm(role),false);assert.match(page,/canMutateCrm\(user\?\.role\)/)})
test('unknown cost differs from zero and decimal overflow is rejected',()=>{assert.equal(u.crmMoney(null),'Unavailable');assert.notEqual(u.crmMoney(0),'Unavailable');for(const cost of ['','0','0.01','99999999999999999.99'])assert.equal(u.validCost(cost),true);for(const cost of ['-1','1e2','0.001','100000000000000000','NaN'])assert.equal(u.validCost(cost),false)})
test('CSV protects formulas and preserves unknown costs and business date',()=>{for(const value of ['=X','+X','-X','@X'])assert.ok(u.csvCell(value).startsWith('"\''));const csv=u.recordsCsv([{recordAt:'2026-01-01',customerName:'=SUM(A1)',cost:null,business_date:'2026-09-15'}]);assert.match(csv,/Unavailable/);assert.match(csv,/2026-09-15/);assert.match(csv,/Recording Business Date/);assert.equal(u.csvCell('a"b'),'"a""b"')})
test('generation rejects late load and selection results',()=>{const gate=u.createGate(),a=gate.next(),b=gate.next();assert.equal(gate.current(a),false);assert.equal(gate.current(b),true);assert.match(page,/detailGate.current.current\(generation\)/);assert.match(form,/gate.current.current\(id\)/)})
test('synchronous duplicate lock, frozen payload, stable uncertain retry and fresh confirmed key',()=>{const s=u.createSubmission(),payload={customerId:'a',cost:'0'},a=s.begin('services',payload);assert.equal(s.begin('services',payload),null);payload.customerId='b';assert.equal(a.payload.customerId,'a');assert.throws(()=>{a.payload.cost=3},TypeError);s.finish(false);const retry=s.begin('services',{customerId:'a',cost:'0'});assert.equal(retry.key,a.key);s.finish(true);assert.notEqual(s.begin('services',{customerId:'a',cost:'0'}).key,a.key)})
test('failed load cannot become authoritative empty or zero',()=>{assert.match(page,/!data\?<p>Authoritative records unavailable/);assert.match(api,/Invalid CRM history/);assert.match(page,/setData\(null\)/)})
test('confirmed mutation remains success after refresh failure',()=>{assert.match(page,/confirmed=true/);assert.match(page,/Record saved successfully\. Refresh failed/);assert.match(page,/submission.current.finish\(confirmed\)/)})
test('hotel reuses persisted API and legacy lifecycle; transport/service have single records',()=>{assert.match(api,/\/hotel-bookings/);assert.match(api,/\/crm\/records/);assert.match(form,/AIRPORT_PICKUP/);assert.match(form,/GIFT.*FOOD.*TICKET.*OTHER/);assert.match(form,/customerSessionId:null/);assert.deepEqual(u.hotelActions('COMPLETED'),[]);assert.deepEqual(u.hotelActions('REQUESTED'),['approve','reject','CANCELLED'])})
test('CRM header and legacy aliases protected',()=>{const layout=fs.readFileSync(new URL('../src/components/layout/MainLayout.jsx',import.meta.url),'utf8');const routes=fs.readFileSync(new URL('../src/routes/AppRoutes.jsx',import.meta.url),'utf8');assert.match(layout,/!isCrm && !isMachine/);for(const path of ['/crm','/crm-gre','/crm-gre/services'])assert.equal(u.isCrmRoute(path),true);for(const path of ['hotel-bookings','vehicles','gifts','services'])assert.ok(routes.includes(`path="/crm-gre/${path}"\n        element={<Navigate to="/crm-gre" replace />}`))})

test('monetary response decoding and display preserve every digit',()=>{const parsed=u.parseCrmResponse('{"cost":99999999999999999.99,"estimatedCost":0.00,"actualCost":null,"description":"\\\"cost\\\":123"}');assert.equal(parsed.cost,'99999999999999999.99');assert.equal(parsed.estimatedCost,'0.00');assert.equal(parsed.actualCost,null);assert.equal(u.crmMoney(parsed.cost),'NPR 99,99,99,99,99,99,99,999.99');assert.match(u.recordsCsv([parsed]),/99999999999999999\.99/);assert.throws(()=>u.parseCrmResponse('not json'));})
test('uncertain keys survive remount and intervening requests; actor namespaces differ',()=>{const memory=new Map(),storage={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)};const a=u.createSubmission({storage,namespace:'alice'});const first=a.begin('services',{customerId:'c',cost:'0'});a.finish(false);const second=a.begin('transport',{customerId:'d'});a.finish(false);const remount=u.createSubmission({storage,namespace:'alice'});assert.equal(remount.begin('services',{customerId:'c',cost:'0'}).key,first.key);remount.finish(true);assert.equal(remount.begin('transport',{customerId:'d'}).key,second.key);remount.finish(false);const other=u.createSubmission({storage,namespace:'bob'});assert.notEqual(other.begin('services',{customerId:'c',cost:'0'}).key,first.key);})
test('failure to persist a retry key prevents submission',()=>{const s=u.createSubmission({storage:{getItem:()=>null,setItem:()=>{throw Error('storage unavailable')}}});assert.throws(()=>s.begin('services',{customerId:'c'}),/storage unavailable/);})
test('tab scopes cannot silently conflict with visible type selection',()=>{assert.equal(u.scopeType('Hotel Stays','FOOD'),'HOTEL');assert.equal(u.scopeType('Transport','HOTEL'),'TRANSPORT');assert.equal(u.scopeType('Services & Gifts','HOTEL'),'SERVICE');assert.equal(u.scopeType('Services & Gifts','TICKET'),'TICKET');assert.equal(u.scopeType('All Records','FOOD'),'FOOD');assert.match(page,/loadGate.current.next\(\);detailGate.current.next\(\);setSelected/);})
test('CSV quotes commas, Unicode, quotes and line breaks while retaining zero/null',()=>{assert.equal(u.csvCell('नेपाली, "name"\nnext'),'"नेपाली, ""name""\nnext"');const csv=u.recordsCsv([{customerName:'@name',description:'a,b',cost:0,business_date:null}]);assert.match(csv,/'@name/);assert.match(csv,/"0"/);assert.match(csv,/"Unavailable"/);})
