export const BILL_STATUSES = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PAID: 'PAID',
  REJECTED: 'REJECTED',
}

export const PAYMENT_METHODS = {
  CASH: 'CASH',
  CHEQUE: 'CHEQUE',
  BANK_TRANSFER: 'BANK_TRANSFER',
  OTHER: 'OTHER',
}

export const EXPENSE_CATEGORIES = {
  PROCUREMENT: 'PROCUREMENT',
  VEHICLE: 'VEHICLE',
  OIL: 'OIL',
  MAINTENANCE: 'MAINTENANCE',
  STORE_PURCHASE: 'STORE_PURCHASE',
  UTILITY: 'UTILITY',
  OTHER: 'OTHER',
}

export const PAYMENT_STATUSES = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
}

export default {
  BILL_STATUSES,
  PAYMENT_METHODS,
  EXPENSE_CATEGORIES,
  PAYMENT_STATUSES,
}
