export const USER_STATUSES = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  LOCKED: 'LOCKED',
}

export const DEPARTMENT_TYPES = {
  CASINO_OPERATIONS: 'CASINO_OPERATIONS',
  RECEPTION: 'RECEPTION',
  CASHIER: 'CASHIER',
  PIT: 'PIT',
  STORE: 'STORE',
  PROCUREMENT: 'PROCUREMENT',
  ACCOUNTS: 'ACCOUNTS',
  MANAGEMENT: 'MANAGEMENT',
  AUDIT: 'AUDIT',
  OTHER: 'OTHER',
}

export const SETTING_KEYS = {
  BUSINESS_DAY_START_TIME: 'BUSINESS_DAY_START_TIME',
  BUSINESS_DAY_END_TIME: 'BUSINESS_DAY_END_TIME',
  CASINO_OPERATION_START_TIME: 'CASINO_OPERATION_START_TIME',
  CASINO_OPERATION_END_TIME: 'CASINO_OPERATION_END_TIME',
  SETTLEMENT_GRACE_UNTIL: 'SETTLEMENT_GRACE_UNTIL',
  SYSTEM_LOCK_START_TIME: 'SYSTEM_LOCK_START_TIME',
  SYSTEM_LOCK_END_TIME: 'SYSTEM_LOCK_END_TIME',
  SYSTEM_LOCK_REASON: 'SYSTEM_LOCK_REASON',
  DIRECTOR_ADMIN_UNLOCK_REQUIRED: 'DIRECTOR_ADMIN_UNLOCK_REQUIRED',
  URGENT_CASH_LIMIT: 'URGENT_CASH_LIMIT',
  HIGH_VALUE_TRANSACTION_THRESHOLD: 'HIGH_VALUE_TRANSACTION_THRESHOLD',
  LOSING_RETURN_REVIEW_REQUIRED: 'LOSING_RETURN_REVIEW_REQUIRED',
  DEFAULT_CURRENCY: 'DEFAULT_CURRENCY',
  EXPORT_ENABLED: 'EXPORT_ENABLED',
  NOTIFICATIONS_ENABLED: 'NOTIFICATIONS_ENABLED',
}

export default {
  USER_STATUSES,
  DEPARTMENT_TYPES,
  SETTING_KEYS,
}
