export const ANALYTICS_MODULES = {
  BUSINESS: 'BUSINESS',
  CASHIER: 'CASHIER',
  PIT: 'PIT',
  STORE: 'STORE',
  ACCOUNTS: 'ACCOUNTS',
  CUSTOMERS: 'CUSTOMERS',
}

export const KPI_TYPES = {
  FINANCIAL: 'FINANCIAL',
  OPERATIONAL: 'OPERATIONAL',
  RISK: 'RISK',
  STOCK: 'STOCK',
  APPROVAL: 'APPROVAL',
  AUDIT: 'AUDIT',
}
