export const AUDIT_MODULES = {
  AUTH: 'AUTH',
  RECEPTION: 'RECEPTION',
  CASHIER: 'CASHIER',
  PIT: 'PIT',
  DIRECTOR: 'DIRECTOR',
  STORE: 'STORE',
  PROCUREMENT: 'PROCUREMENT',
  ACCOUNTS: 'ACCOUNTS',
  REPORTS: 'REPORTS',
  BUSINESS_STATUS: 'BUSINESS_STATUS',
  SYSTEM_LOCK: 'SYSTEM_LOCK',
  ADMIN: 'ADMIN',
  AUDIT: 'AUDIT',
}

export const AUDIT_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  VIEW: 'VIEW',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  REVIEW: 'REVIEW',
  EXPORT: 'EXPORT',
  SYSTEM_UNLOCK_REQUEST: 'SYSTEM_UNLOCK_REQUEST',
  SYSTEM_UNLOCK: 'SYSTEM_UNLOCK',
  OPEN_SESSION: 'OPEN_SESSION',
  CLOSE_SESSION: 'CLOSE_SESSION',
  PAYMENT_RECORDED: 'PAYMENT_RECORDED',
  BILL_VERIFIED: 'BILL_VERIFIED',
  BILL_REJECTED: 'BILL_REJECTED',
}

export const AUDIT_SEVERITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
}

export default {
  AUDIT_MODULES,
  AUDIT_ACTIONS,
  AUDIT_SEVERITY,
}
