export const APPROVAL_STATUSES = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
}

export const APPROVAL_TYPES = {
  HIGH_VALUE_TRANSACTION: 'HIGH_VALUE_TRANSACTION',
  SYSTEM_UNLOCK: 'SYSTEM_UNLOCK',
  TABLE_REVIEW: 'TABLE_REVIEW',
  MANUAL_CORRECTION: 'MANUAL_CORRECTION',
  PURCHASE_REQUEST: 'PURCHASE_REQUEST',
}

export const ALERT_TYPES = {
  HIGH_VALUE_BUY_IN: 'HIGH_VALUE_BUY_IN',
  HIGH_VALUE_CASH_OUT: 'HIGH_VALUE_CASH_OUT',
  SUSPICIOUS_CUSTOMER: 'SUSPICIOUS_CUSTOMER',
  WATCHLIST_CUSTOMER: 'WATCHLIST_CUSTOMER',
  TABLE_PENDING_REVIEW: 'TABLE_PENDING_REVIEW',
  SYSTEM_UNLOCK_REQUEST: 'SYSTEM_UNLOCK_REQUEST',
}

export const ALERT_STATUSES = {
  OPEN: 'OPEN',
  REVIEWED: 'REVIEWED',
  DISMISSED: 'DISMISSED',
}
