export const NOTIFICATION_TYPES = {
  INFO: 'INFO',
  SUCCESS: 'SUCCESS',
  WARNING: 'WARNING',
  DANGER: 'DANGER',
  APPROVAL: 'APPROVAL',
  ALERT: 'ALERT',
  SYSTEM_LOCK: 'SYSTEM_LOCK',
  BUSINESS_DATE: 'BUSINESS_DATE',
  STORE: 'STORE',
  ACCOUNTS: 'ACCOUNTS',
  CASHIER: 'CASHIER',
  PIT: 'PIT',
  AUDIT: 'AUDIT',
}

export const NOTIFICATION_STATUSES = {
  UNREAD: 'UNREAD',
  READ: 'READ',
}

export const NOTIFICATION_PRIORITIES = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
}

export default {
  NOTIFICATION_TYPES,
  NOTIFICATION_STATUSES,
  NOTIFICATION_PRIORITIES,
}
