import { ROLES } from './roles'

export const ALL_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.DIRECTOR,
  ROLES.ADMIN,
  ROLES.RECEPTIONIST,
  ROLES.CASHIER,
  ROLES.PIT_BOSS,
  ROLES.PIT_SUPERVISOR,
  ROLES.DEALER,
  ROLES.STORE_KEEPER,
  ROLES.PROCUREMENT,
  ROLES.ACCOUNTS,
  ROLES.DEPARTMENT_HEAD,
  ROLES.AUDITOR,
]

export const MANAGEMENT_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.DIRECTOR,
  ROLES.ADMIN,
]

export const ADMIN_ROLES = [ROLES.SUPER_ADMIN, ROLES.ADMIN]

export const CASHIER_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.DIRECTOR,
  ROLES.ADMIN,
  ROLES.CASHIER,
]

export const CHIP_CONTROL_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.DIRECTOR,
  ROLES.CASHIER,
  ROLES.PIT_SUPERVISOR,
]

export const RECEPTION_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.DIRECTOR,
  ROLES.ADMIN,
  ROLES.RECEPTIONIST,
]

export const STORE_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.DIRECTOR,
  ROLES.ADMIN,
  ROLES.STORE_KEEPER,
]

export const PROCUREMENT_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.DIRECTOR,
  ROLES.ADMIN,
  ROLES.PROCUREMENT,
]

export const ACCOUNTS_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.DIRECTOR,
  ROLES.ADMIN,
  ROLES.ACCOUNTS,
]

export const PIT_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.PIT_SUPERVISOR,
  ROLES.DEALER,
]

export const AUDIT_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.DIRECTOR,
  ROLES.ADMIN,
  ROLES.AUDITOR,
]
