export const GAME_TYPES = {
  BACCARAT: 'BACCARAT',
  BLACKJACK: 'BLACKJACK',
  ROULETTE: 'ROULETTE',
  SLOT: 'SLOT',
  DRAGON_TIGER: 'DRAGON_TIGER',
  POKER: 'POKER',
  OTHER: 'OTHER',
}

export const TABLE_STATUSES = {
  AVAILABLE: 'AVAILABLE',
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  MAINTENANCE: 'MAINTENANCE',
}

export const TABLE_SESSION_STATUSES = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  PENDING_REVIEW: 'PENDING_REVIEW',
}
