import { GAME_TYPES, TABLE_STATUSES } from './pitConstants'

export const PIT_MOCK_TABLES = [
  {
    id: '1',
    tableCode: 'TBL-001',
    tableName: 'Baccarat Main 1',
    gameType: GAME_TYPES.BACCARAT,
    location: 'Main Floor A',
    status: TABLE_STATUSES.AVAILABLE,
    minimumBet: 1000,
    maximumBet: 200000,
    remarks: 'Primary baccarat table.',
  },
  {
    id: '2',
    tableCode: 'TBL-002',
    tableName: 'Blackjack 1',
    gameType: GAME_TYPES.BLACKJACK,
    location: 'Main Floor B',
    status: TABLE_STATUSES.AVAILABLE,
    minimumBet: 500,
    maximumBet: 100000,
    remarks: 'Standard blackjack table.',
  },
  {
    id: '3',
    tableCode: 'TBL-003',
    tableName: 'Roulette 1',
    gameType: GAME_TYPES.ROULETTE,
    location: 'Main Floor C',
    status: TABLE_STATUSES.CLOSED,
    minimumBet: 500,
    maximumBet: 75000,
    remarks: 'Closed until next shift.',
  },
  {
    id: '4',
    tableCode: 'TBL-004',
    tableName: 'Dragon Tiger VIP',
    gameType: GAME_TYPES.DRAGON_TIGER,
    location: 'VIP Room',
    status: TABLE_STATUSES.OPEN,
    minimumBet: 5000,
    maximumBet: 500000,
    remarks: 'VIP table.',
  },
  {
    id: '5',
    tableCode: 'TBL-005',
    tableName: 'Poker 1',
    gameType: GAME_TYPES.POKER,
    location: 'Poker Room',
    status: TABLE_STATUSES.AVAILABLE,
    minimumBet: 1000,
    maximumBet: 150000,
    remarks: 'Poker room table.',
  },
  {
    id: '6',
    tableCode: 'TBL-006',
    tableName: 'Slot Zone A',
    gameType: GAME_TYPES.SLOT,
    location: 'Slot Area',
    status: TABLE_STATUSES.MAINTENANCE,
    minimumBet: 100,
    maximumBet: 50000,
    remarks: 'Under machine inspection.',
  },
]

export default PIT_MOCK_TABLES
