export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  DIRECTOR: 'DIRECTOR',
  ADMIN: 'ADMIN',
  RECEPTIONIST: 'RECEPTIONIST',
  CASHIER: 'CASHIER',
  PIT_SUPERVISOR: 'PIT_SUPERVISOR',
  DEALER: 'DEALER',
  STORE_KEEPER: 'STORE_KEEPER',
  PROCUREMENT: 'PROCUREMENT',
  ACCOUNTS: 'ACCOUNTS',
  STORE_MANAGER: 'STORE_MANAGER',
  ACCOUNTANT_HEAD: 'ACCOUNTANT_HEAD',
  ACCOUNTS_MANAGER: 'ACCOUNTS_MANAGER',
  DEPARTMENT_HEAD: 'DEPARTMENT_HEAD',
  AUDITOR: 'AUDITOR',
}

export default ROLES
