import { ROLES } from './roles'
import {
  ACCOUNTS_ROLES,
  ADMIN_ROLES,
  ALL_ROLES,
  AUDIT_ROLES,
  CASHIER_ROLES,
  CHIP_CONTROL_ROLES,
  MANAGEMENT_ROLES,
  PIT_ROLES,
  PROCUREMENT_ROLES,
  RECEPTION_ROLES,
  STORE_ROLES,
} from './permissions'

const DEPARTMENT_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.DIRECTOR,
  ROLES.ADMIN,
  ROLES.DEPARTMENT_HEAD,
]

const REPORT_ROLES = [ROLES.SUPER_ADMIN, ROLES.DIRECTOR, ROLES.ADMIN, ROLES.AUDITOR]
const DIRECTOR_ROLES = [ROLES.SUPER_ADMIN, ROLES.DIRECTOR, ROLES.ADMIN]
const CASHIER_RECONCILIATION_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.DIRECTOR,
  ROLES.CASHIER,
]

export const ROUTE_PERMISSIONS = {
  '/dashboard': ALL_ROLES,
  '/notifications': ALL_ROLES,
  '/admin/users': ADMIN_ROLES,
  '/admin/roles': ADMIN_ROLES,
  '/admin/departments': ADMIN_ROLES,
  '/admin/business-date': ADMIN_ROLES,
  '/admin/system-lock': ADMIN_ROLES,
  '/admin/settings': ADMIN_ROLES,
  '/admin/permissions': ADMIN_ROLES,
  '/demo/control-panel': ADMIN_ROLES,
  '/director/approvals': DIRECTOR_ROLES,
  '/director/high-value-alerts': DIRECTOR_ROLES,
  '/director/suspicious-alerts': DIRECTOR_ROLES,
  '/director/approval-history': DIRECTOR_ROLES,
  '/director/system-unlock': DIRECTOR_ROLES,
  '/reception': RECEPTION_ROLES,
  '/reception/customers/new': RECEPTION_ROLES,
  '/reception/customers/search': RECEPTION_ROLES,
  '/reception/customers/:id': RECEPTION_ROLES,
  '/reception/customers/:id/edit': RECEPTION_ROLES,
  '/cashier/buy-in': CASHIER_ROLES,
  '/chip-control': CHIP_CONTROL_ROLES,
  '/cashier/cash-out': CASHIER_ROLES,
  '/cashier/wallet-transactions': CASHIER_ROLES,
  '/cashier/daily-report': CASHIER_ROLES,
  '/cashier/reconciliation': CASHIER_RECONCILIATION_ROLES,
  '/pit/tables': PIT_ROLES,
  '/pit/open-sessions': PIT_ROLES,
  '/pit/close-sessions': PIT_ROLES,
  '/pit/table-reports': PIT_ROLES,
  '/pit/sessions/:id': PIT_ROLES,
  '/store/department-requests': STORE_ROLES,
  '/store/requests/new': [...STORE_ROLES, ROLES.DEPARTMENT_HEAD],
  '/store/review': STORE_ROLES,
  '/store/stock': STORE_ROLES,
  '/store/delivery-receive': STORE_ROLES,
  '/procurement/list': PROCUREMENT_ROLES,
  '/procurement/vendor-quotations': PROCUREMENT_ROLES,
  '/procurement/purchase-orders': PROCUREMENT_ROLES,
  '/accounts/bills': ACCOUNTS_ROLES,
  '/accounts/cash-expenses': ACCOUNTS_ROLES,
  '/accounts/cheque-payments': ACCOUNTS_ROLES,
  '/accounts/vendor-payments': ACCOUNTS_ROLES,
  '/accounts/reports': ACCOUNTS_ROLES,
  '/department/my-requests': DEPARTMENT_ROLES,
  '/department/confirm-received': DEPARTMENT_ROLES,
  '/audit-logs': AUDIT_ROLES,
  '/audit-logs/:id': AUDIT_ROLES,
  '/audit/reports': AUDIT_ROLES,
  '/analytics/management': REPORT_ROLES,
  '/testing/checklist': REPORT_ROLES,
  '/reports': REPORT_ROLES,
  '/reports/daily-business': REPORT_ROLES,
  '/reports/customer-transactions': REPORT_ROLES,
  '/reports/transactions': REPORT_ROLES,
  '/reports/losing-return-preview': REPORT_ROLES,
}

export default ROUTE_PERMISSIONS
