export const REQUEST_TYPES = {
  NORMAL: 'NORMAL',
  URGENT: 'URGENT',
  NEXT_DAY: 'NEXT_DAY',
}

export const REQUEST_STATUSES = {
  PENDING_STORE_REVIEW: 'PENDING_STORE_REVIEW',
  STOCK_AVAILABLE: 'STOCK_AVAILABLE',
  STOCK_ISSUED: 'STOCK_ISSUED',
  PROCUREMENT_REQUIRED: 'PROCUREMENT_REQUIRED',
  PENDING_DIRECTOR_APPROVAL: 'PENDING_DIRECTOR_APPROVAL',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  ORDERED: 'ORDERED',
  PARTIALLY_DELIVERED: 'PARTIALLY_DELIVERED',
  FULLY_DELIVERED: 'FULLY_DELIVERED',
  PENDING_DEPARTMENT_CONFIRMATION: 'PENDING_DEPARTMENT_CONFIRMATION',
  CONFIRMED_RECEIVED: 'CONFIRMED_RECEIVED',
  CLOSED: 'CLOSED',
}

export const STOCK_STATUSES = {
  IN_STOCK: 'IN_STOCK',
  LOW_STOCK: 'LOW_STOCK',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
}

export const DELIVERY_STATUSES = {
  PENDING: 'PENDING',
  PARTIAL: 'PARTIAL',
  FULL: 'FULL',
}

export default {
  REQUEST_TYPES,
  REQUEST_STATUSES,
  STOCK_STATUSES,
  DELIVERY_STATUSES,
}
