export const TRANSACTION_TYPES = {
  BUY_IN: 'BUY_IN',
  CASH_OUT: 'CASH_OUT',
  ADJUSTMENT: 'ADJUSTMENT',
}

export const BUY_IN = TRANSACTION_TYPES.BUY_IN
export const CASH_OUT = TRANSACTION_TYPES.CASH_OUT
export const ADJUSTMENT = TRANSACTION_TYPES.ADJUSTMENT

export const PAYMENT_METHODS = {
  CASH: 'CASH',
  CARD: 'CARD',
  BANK_TRANSFER: 'BANK_TRANSFER',
  COMPLIMENTARY: 'COMPLIMENTARY',
  OTHER: 'OTHER',
}

export const CASH = PAYMENT_METHODS.CASH
export const CARD = PAYMENT_METHODS.CARD
export const BANK_TRANSFER = PAYMENT_METHODS.BANK_TRANSFER
export const COMPLIMENTARY = PAYMENT_METHODS.COMPLIMENTARY
export const OTHER = PAYMENT_METHODS.OTHER
