import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import useAuth from '../../hooks/useAuth'
import api from '../../api/crmApi'
import CrmRecordForm from './CrmRecordForm'
import { CRM_TABS, canMutateCrm, crmMoney, createGate, createSubmission, recordsCsv, hotelActions, validCost, scopeType } from '../../utils/crm'
const errorText = e => e.response?.data?.message || e.message || 'CRM unavailable'
export default function CrmGreMarketing() {
 const { user } = useAuth(), mutate = canMutateCrm(user?.role)
 const [tab,setTab]=useState('Overview'),[filters,setFilters]=useState({q:'',type:'',status:'',from:'',to:''}),[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[selected,setSelected]=useState(null),[hotel,setHotel]=useState(null),[detailError,setDetailError]=useState(''),[busy,setBusy]=useState(false),[formKey,setFormKey]=useState(0),[actual,setActual]=useState('')
 const loadGate=useRef(createGate()),detailGate=useRef(createGate()),submission=useMemo(()=>({current:createSubmission({ namespace: user?.id || user?.username, requireStorage: true })}),[user?.id,user?.username]),mounted=useRef(true)
 const reload = useCallback(async () => { const generation=loadGate.current.next();detailGate.current.next();setSelected(null);setHotel(null);setActual('');setData(null);setLoading(true);setError('')
  try { const value=await api.records(Object.fromEntries(Object.entries({...filters,type:scopeType(tab,filters.type)}).filter(([,v])=>v!==''))); if(loadGate.current.current(generation)&&mounted.current)setData(value) }
  catch(e){if(loadGate.current.current(generation)&&mounted.current)setError(errorText(e));throw e}
  finally{if(loadGate.current.current(generation)&&mounted.current)setLoading(false)}
 },[filters,tab])
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;loadGate.current.next();detailGate.current.next()}},[])
 useEffect(()=>{reload().catch(()=>{})},[reload])
 const choose=async row=>{const generation=detailGate.current.next();setSelected(row);setHotel(null);setDetailError('');setActual('');if(row.recordType==='HOTEL')try{const value=await api.hotel(row.id);if(detailGate.current.current(generation)&&mounted.current)setHotel(value)}catch(e){if(detailGate.current.current(generation)&&mounted.current)setDetailError(errorText(e))}}
 const perform=async(target,payload,operation,retry=false)=>{if(!mutate)return;let frozen;try{frozen=submission.current.begin(target,payload,retry)}catch(e){setError(errorText(e));return}if(!frozen)return;setBusy(true);setMessage('');setError('');let confirmed=false
  try{await operation(frozen);confirmed=true;if(mounted.current){setMessage('Record saved successfully.');setFormKey(v=>v+1);try{await reload()}catch{setMessage('Record saved successfully. Refresh failed; reload to see current records.')}}}
  catch(e){if(mounted.current)setError(errorText(e))}finally{submission.current.finish(confirmed);if(mounted.current)setBusy(false)}}
 const save=(kind,payload,retry=false)=>perform(`create:${kind}`,payload,f=>kind==='hotel'?api.createHotel({...f.payload,idempotencyKey:f.key}):api.create(kind,{...f.payload,idempotencyKey:f.key}),retry)
 const change=(status)=>{const row=selected;if(!row)return;const kind=row.recordType==='TRANSPORT'?'transport':'services';perform(`${kind}:${row.id}`,{status,expectedVersion:row.version},f=>api.status(kind,row.id,f.payload))}
 const hotelChange=(action)=>{const id=hotel.id;if(action==='COMPLETED'&&(!validCost(actual)||actual===''))return setError('Enter a valid actual cost.');const payload=action==='approve'||action==='reject'?{}:{status:action,actualCost:action==='COMPLETED'?actual:null};perform(`hotel:${id}:${action}`,payload,f=>api.hotelAction(id,action==='approve'||action==='reject'?action:'status',f.payload))}
 let pendingCreates=[], recoveryError=''
 try { pendingCreates=submission.current.pendingCreates() } catch(e) { recoveryError=e.message }
 const discardPending=p=>{if(!window.confirm('Discarding the local recovery record does NOT reverse a transaction that may already have completed on the server.'))return;try{submission.current.discard(p.signature);setMessage('Local recovery record discarded. Check authoritative records before creating a new record.')}catch(e){setError(e.message)}}
 const rows=useMemo(()=>{const all=data?.records||[];return tab==='Hotel Stays'?all.filter(r=>r.recordType==='HOTEL'):tab==='Transport'?all.filter(r=>r.recordType==='TRANSPORT'):tab==='Services & Gifts'?all.filter(r=>!['HOTEL','TRANSPORT'].includes(r.recordType)):all},[data,tab])
 const updateFilters=change=>{loadGate.current.next();detailGate.current.next();setSelected(null);setHotel(null);setData(null);setLoading(true);setFilters(f=>({...f,...change}))}
 const exportCsv=()=>{const url=URL.createObjectURL(new Blob([recordsCsv(rows)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='crm-records.csv';a.click();URL.revokeObjectURL(url)}
 return <div className="space-y-5 text-slate-900"><h1 className="text-3xl font-bold">CRM / GRE</h1><p className="text-sm text-slate-600">Informational guest-service records. Times are Kathmandu local time. Recording Business Date: {data?.recordingBusinessDate||'Unavailable'}.</p>
 {recoveryError&&<p role="alert">Recovery unavailable: {recoveryError}</p>}
 {mutate&&pendingCreates.map(p=><section key={p.key} className="rounded-lg border border-amber-400 bg-amber-50 p-3"><strong>OUTCOME UNCERTAIN</strong><p>{p.target} · Customer {p.payload.customerId} · {p.payload.description||p.payload.hotelName||'Saved guest-service record'} · Recording-date policy applies · {p.createdAt || 'Pending timestamp unavailable for older saved record'}</p><button disabled={busy} onClick={()=>save(p.target.slice(7),p.payload,true)}>Retry Original</button><button disabled={busy} className="ml-4" onClick={()=>discardPending(p)}>Discard Local Pending Operation</button></section>)}
 <nav className="flex flex-wrap gap-2">{CRM_TABS.map(t=><button disabled={busy} key={t} onClick={()=>{loadGate.current.next();detailGate.current.next();setSelected(null);setHotel(null);setData(null);setFilters(f=>({...f,type:''}));setTab(t)}} className={`rounded-lg border px-4 py-2 ${tab===t?'bg-amber-400':'bg-white'}`}>{t}</button>)}</nav>
 <div className="flex flex-wrap gap-2 rounded-xl border bg-white p-3"><input disabled={busy} aria-label="Search records" placeholder="Search customer or description" value={filters.q} onChange={e=>updateFilters({q:e.target.value})}/><select disabled={busy||tab==='Hotel Stays'||tab==='Transport'} aria-label="Record type" value={tab==='Hotel Stays'?'HOTEL':tab==='Transport'?'TRANSPORT':filters.type} onChange={e=>updateFilters({type:e.target.value})}><option value="">All types</option>{(tab==='Services & Gifts'?['GIFT','FOOD','TICKET','OTHER']:['HOTEL','TRANSPORT','GIFT','FOOD','TICKET','OTHER']).map(t=><option key={t}>{t}</option>)}</select><select disabled={busy} aria-label="Status" value={filters.status} onChange={e=>updateFilters({status:e.target.value})}><option value="">All statuses</option>{['REQUESTED','APPROVED','BOOKED','CHECKED_IN','SCHEDULED','COMPLETED','CANCELLED','REJECTED'].map(s=><option key={s}>{s}</option>)}</select>{['from','to'].map(k=><label key={k}>{k}<input disabled={busy} type="date" value={filters[k]} onChange={e=>updateFilters({[k]:e.target.value})}/></label>)}<button disabled={busy} onClick={()=>reload().catch(()=>{})}>Refresh</button></div>
 <p className="text-xs text-slate-500">At most 100 matching records, ordered by service/scheduled/check-in date. Counts describe the loaded scope; they are not all-time totals. Hotel costs use actual when known, otherwise estimated. Legacy service records remain in legacy reports.</p>
 {message&&<p role="status" className="rounded-lg bg-emerald-50 p-3 text-emerald-800">{message}</p>}{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-red-700">{error}</p>}
 {loading?<p>Loading records…</p>:!data?<p>Authoritative records unavailable.</p>:<>
 {tab==='Hotel Stays'&&<p className="rounded-xl border bg-white p-4 text-sm">Loaded hotel records: {rows.length} · Requested: {rows.filter(r=>r.status==='REQUESTED').length} · Checked in: {rows.filter(r=>r.status==='CHECKED_IN').length} · Completed: {rows.filter(r=>r.status==='COMPLETED').length}. Status counts describe persisted records, not inferred occupancy.</p>}
 {tab==='Overview'&&<div className="grid gap-3 md:grid-cols-3">{[['Hotel records',rows.filter(r=>r.recordType==='HOTEL').length],['Scheduled transport',rows.filter(r=>r.recordType==='TRANSPORT'&&r.status==='SCHEDULED').length],['Services & gifts',rows.filter(r=>!['HOTEL','TRANSPORT'].includes(r.recordType)).length]].map(([label,value])=><div key={label} className="rounded-xl border bg-white p-4"><p>{label} — loaded scope</p><b className="text-2xl">{value}</b></div>)}</div>}
 <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_340px]"><div className="overflow-auto rounded-xl border bg-white p-3"><div className="mb-3 flex justify-between"><h2 className="font-bold">{tab==='Overview'?'Recent activity (by record date)':tab} · {rows.length} loaded</h2>{tab==='All Records'&&<button onClick={exportCsv}>Export loaded CSV</button>}</div><table className="w-full text-left text-sm"><thead><tr>{['Date','Customer / code','Type','Description','Cost','Staff','Status'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{(tab==='Overview'?rows.slice(0,10):rows).map(row=><tr key={`${row.recordType}:${row.id}`} className="border-t"><td className="p-2"><button disabled={busy} className="text-amber-800 underline" onClick={()=>choose(row)}>{String(row.recordAt).replace('T',' ').slice(0,16)}</button></td><td>{row.customerName||'Unavailable'}<br/>{row.customerCode||'Unavailable'}</td><td>{row.recordType}</td><td>{row.description}</td><td>{crmMoney(row.cost)}<br/>{row.costBasis}</td><td>{row.staff||'Unavailable'}</td><td>{row.status}</td></tr>)}</tbody></table>{rows.length===0&&<p className="p-5">No records in this scope.</p>}</div>
 <aside className="space-y-4">{mutate&&['Hotel Stays','Transport','Services & Gifts'].includes(tab)&&<CrmRecordForm key={`${tab}:${formKey}`} kind={tab==='Hotel Stays'?'hotel':tab==='Transport'?'transport':'services'} busy={busy} onSave={save}/>}
 {selected&&<div className="space-y-2 rounded-xl border bg-white p-4"><h2 className="font-bold">Selected record</h2><p>{selected.reference}</p><p>{selected.customerName} · {selected.customerCode}</p><p>{selected.description}</p><p>Status: {selected.status}</p><p>Recording Business Date: {selected.business_date||'Unavailable'}</p><p>Classification: {selected.classification||'Unspecified'}</p>{['transportType','pickup','destination','vehicle','driver','notes'].map(k=>selected[k]&&<p key={k}>{k}: {selected[k]}</p>)}
 {detailError&&<p role="alert">{detailError}</p>}{selected.recordType==='HOTEL'&&!hotel&&!detailError&&<p>Loading hotel detail…</p>}{hotel&&<><p>Stay: {hotel.checkInDate} → {hotel.checkOutDate}</p><p>Guests: {hotel.numberOfGuests}</p><p>Estimated: {crmMoney(hotel.estimatedCost)} · Actual: {crmMoney(hotel.actualCost)}</p><p>Recorded by: {hotel.createdBy?.username||'Unavailable'}</p>{mutate&&hotel.status==='CHECKED_IN'&&<input aria-label="Actual cost" disabled={busy} value={actual} onChange={e=>setActual(e.target.value)} placeholder="Actual cost NPR"/>}{mutate&&hotelActions(hotel.status).map(a=><button disabled={busy} className="mr-2 rounded border p-2" key={a} onClick={()=>hotelChange(a)}>{a}</button>)}</>}
 {mutate&&selected.recordType!=='HOTEL'&&(selected.recordType==='TRANSPORT'?selected.status==='SCHEDULED':selected.status==='COMPLETED')&&<>{selected.recordType==='TRANSPORT'&&<button disabled={busy} onClick={()=>change('COMPLETED')}>Complete</button>}<button disabled={busy} className="ml-3" onClick={()=>change('CANCELLED')}>Cancel</button></>}
 </div>}</aside></div></>}
 </div>
}
